### PR TITLE
Added synirc to default services.cfg and some more example vanilla commands.

### PR DESCRIPTION
**Pull request by sandalle**
Let me know if you'd like me to add more vanilla commands. I have many of them already written out for my own use ( http://pastebin.com/7XwEtkXc ). Thank you for the mod, it helps us out a lot! :)

### CODE REVIEW

**Comment by blay09** [comment]
Two issues: missing a quotation mark at the [start of synirc's IDENTIFY command](https://github.com/sandalle/EiraIRC/commit/f8eb66825b6a860b82a37b3ac07cc85325ba5726#diff-3c1cf8e3d01020dc9fb8273f442001f9R33) and referencing the [wrong JsonObject (tps)](https://github.com/sandalle/EiraIRC/commit/b65f803f755e9b8f2a96b6f734c1399f3b53533f#diff-f60e8c52304480852ca1151516fb2a6cR179) when adding the properties when it should be ban, banip, etc. instead.

Nice pastebin you got there, I might reference that on the [help page](http://blay09.net/?page_id=63) I'm working on every now and then. :)

**Comment by sandalle** [comment]
Derp, sorry about that. I'll blame the late hour (2AM). :) Feel free to copy/paste/modify entries from the pastebin. :)

**Comment by sandalle** [comment]
I haven't used GitHub pull requests, so hopefully that typo fix is included in the merge. ;) Let me know if you'd like me to add the rest from my pastebin or if you have any requests for more.

**Comment by blay09** [comment]
Thanks for the contribution, gonna merge it in. I think more example commands than that would make the example file too crowded, so this should be good enough now.

**Pull request merged**
